### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by akhilanandbv003** [iit-cs429/assignments#2]
I am getting this error , when i tried to run the code as a whole.Please help.

Traceback (most recent call last):
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 31, in **init**
    self.documents = self.read_lines(filename)
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 235, in read_lines
    return [l.strip() for l in gzip.open(filename, 'rt').readlines()]
  File "C:\Anaconda\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "C:\Anaconda\lib\gzip.py", line 94, in **init**
    fileobj = self.myfileobj = **builtin**.open(filename, mode or 'rb')
ValueError: Invalid mode ('rtb')

PS: I have not modified any of the code given by professor

**Comment by karthikbmk** [comment]
Guess you are using Python 2x. Try with 3.5

**Comment by akhilanandbv003** [comment]
Upgraded to 3.5. Error persists.But 1 new error.
Traceback (most recent call last):
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 260, in <module>
    main()
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 252, in main
    indexer = Index('documents.txt.gz')
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 31, in **init**
    self.documents = self.read_lines(filename)
  File "C:\Users\Akhilanand\Documents\GitHub\akhilanandbv003\a1\searcher.py", line 235, in read_lines
    return [l.strip() for l in gzip.open(filename, 'rt').readlines()]
  File "C:\Users\Akhilanand\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 710: character maps to <undefined>

**Comment by karthikbmk** [comment]
modify open function :

gzip.open(filename, 'rt', **encoding="utf8"**)

**Comment by akhilanandbv003** [comment]
It worked. Thank you so much
