### ISSUE TITLE
doctest in scores.py

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/assignments#5]
I am getting this error when I try to run the scores.py doctest: 

File "/Users/camilagarciahernandez/Documents/Universidad/Iit/infret/cgarciahdez/a2/score.py", line 27, in score.idf
Failed example:
    idf('e', idx) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest score.idf[3]>", line 1, in <module>
        idf('e', idx) # doctest:+ELLIPSIS
    NameError: name 'idx' is not defined

which is clear, because I can see that it is defined in the comment as index.Index(). What could be causing this?

**Comment by cgarciahdez** [comment]
Just noticed the error begins in the creation of the index:

File "/Users/camilagarciahernandez/Documents/Universidad/Iit/infret/cgarciahdez/a2/score.py", line 22, in score.idf
Failed example:
    idx = index.Index(['a b c a', 'c d e', 'c e f'])
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/doctest.py", line 1320, in **run
        compileflags, 1), test.globs)
      File "<doctest score.idf[0]>", line 1, in <module>
        idx = index.Index(['a b c a', 'c d e', 'c e f'])
      File "/Users/camilagarciahernandez/Documents/Universidad/Iit/infret/cgarciahdez/a2/index.py", line 21, in __init**
        self.doc_lengths, self.mean_doc_length = self.compute_doc_lengths(self.index)
    TypeError: 'NoneType' object is not iterable

Does this happen because I have not filled out my index class yet?

**Comment by aronwc** [comment]
Yes.
